services:
  # Backend Service
  - type: web
    name: quickbird-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && alembic upgrade head
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quickbird-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production

  # Database
  - type: pserv
    name: quickbird-db
    plan: free
    databaseName: quickbird
    user: quickbird
