"""Add clients, invoices, milestones, and work_logs models

Revision ID: 3b8df3e4d79f
Revises: da15a678941e
Create Date: 2025-09-13 13:41:19.612283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8df3e4d79f'
down_revision = 'da15a678941e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns without foreign key constraints (SQLite limitation)
    op.add_column('projects', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('milestone_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'milestone_id')
    op.drop_column('projects', 'client_id')
    # ### end Alembic commands ###