"""Add notifications model

Revision ID: 94937adc3e27
Revises: 3b8df3e4d79f
Create Date: 2025-09-13 15:33:05.432877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94937adc3e27'
down_revision = '3b8df3e4d79f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'projects', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'milestones', ['milestone_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    # ### end Alembic commands ###
