"""Add notifications model

Revision ID: 94937adc3e27
Revises: 3b8df3e4d79f
Create Date: 2025-09-13 15:33:05.432877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94937adc3e27'
down_revision = '3b8df3e4d79f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Foreign key constraints removed for SQLite compatibility
    # The relationships are enforced at the application level by SQLAlchemy
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Foreign key constraints removed for SQLite compatibility
    pass
    # ### end Alembic commands ###
